### ISSUE TITLE
CI/CD

### ISSUE THREAD

**Issue by Jazmusic1234** [cse112-sp22-group5/cse112-sp22-group5#2]
## Issue Info
The pipeline needs to be put into working condition. Additionally, whenever possible, upgrades to the pipeline is welcome.

## Tasks
- [x] Separate workflows for pull requests and push
- A push would cause a firebase deployment
- [x] Separate workflows for dev and master branches
- [x] Set up local listing, formatting, and commit linting
- Encountering issues using lint-staged, could just not use lint-staged (git staged files)
- [x] Add firebase previews to PR workflows (preview site does not work right now)
- [x] Deploy JSDocs (gh-pages is created, now we need firebase to host that index.html on a docs site)
- [x] Restructure testing and doc folders
- [x] Code quality
- [ ] Automate Code Coverage to github action

Just to have it documented and written down:

- We created PR workflows
- We added Firebase Preview
  - Although, we need to change index.html to host the front page of the site
- We set up Codacy
  - Although, we need to make sure it comes up as a check on all PRs
  - Make sure it ignores directories that do not need to be checked
  - Have some other checks besides just linting
- We added JSDocs
  - But firebase needs to host the gh-pages index.html on a different docs site
- DID NOT restructure the test folder as doing so causes path issues that would require additional work
- DID NOT set up local linting yet since lint-staged is causing issues

**Comment by Jazmusic1234** [comment]
- [ ] Make diagram
- [ ] Make wiki page for Ci/CD
