### ISSUE TITLE
Task list

### ISSUE THREAD

**Issue by Jazmusic1234** [cse112-sp22-group5/cse112-sp22-group5#6]
[Miro Board](https://miro.com/app/board/uXjVO4ohqeU=/?share_link_id=118642427279)

**Comment by dnthem** [comment]
Check list:
- [ ] Add task button
- [ ] Edit task button
- [ ] Save button
- [ ] Canel button
- [ ] Clear tasks
- [ ] Clear completed tasks
- [ ] Check off/cross off tasks
- [ ] Select current working task to display

**Comment by Jazmusic1234** [comment]
- [ ] Form should show when Edit button is clicked
